name: Build docker and upload to registry

on:
  push:
    tags:
      # strict semver regex
      - '*'

env:
  CIRCLES_CI_DO_TOKEN: ${{ secrets.CIRCLES_CI_DO_TOKEN }}

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: |
          sudo snap install doctl
          sudo snap connect doctl:dot-docker
      - name: Configure auth
        run: |
          doctl auth init -t ${CIRCLES_CI_DO_TOKEN}
      - name: Checkout
        uses: actions/checkout@main
      - name: Get ref
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" 
          echo ${{ env.RELEASE_VERSION }}
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: parse_ref
      - name: Docker build and tag
        env:
          IMAGE_VERSION: ${{ steps.parse_ref.outputs.tag }}
        run: |
          echo $IMAGE_VERSION
          echo ${{ env.IMAGE_VERSION }}
           echo ${{ steps.vars.parse_ref.outputs.tag }}
          docker build -t registry.digitalocean.com/circles-registry/subgraph:${IMAGE_VERSION} .
      - name: Registry login
        run: |
          doctl registry login
      - name: Docker push
        env:
          IMAGE_VERSION: ${{ steps.parse_ref.outputs.tag }}
        run: |
          docker push registry.digitalocean.com/circles-registry/subgraph:${IMAGE_VERSION}
